package vbase

import (
	"io"
	"time"

	"github.com/imajinyun/go-knifer/internal/base"
)

// Code generated by internal facade audit; DO NOT EDIT.

// SliceIsEmpty delegates to the internal base implementation.
func SliceIsEmpty[T any](a []T) bool {
	return base.SliceIsEmpty(a)
}

// SliceIsNotEmpty delegates to the internal base implementation.
func SliceIsNotEmpty[T any](a []T) bool {
	return base.SliceIsNotEmpty(a)
}

// SliceIndexOf delegates to the internal base implementation.
func SliceIndexOf[T comparable](a []T, v T) int {
	return base.SliceIndexOf(a, v)
}

// SliceLastIndexOf delegates to the internal base implementation.
func SliceLastIndexOf[T comparable](a []T, v T) int {
	return base.SliceLastIndexOf(a, v)
}

// SliceReverse delegates to the internal base implementation.
func SliceReverse[T any](a []T) []T {
	return base.SliceReverse(a)
}

// SliceJoin delegates to the internal base implementation.
func SliceJoin[T any](a []T, sep string) string {
	return base.SliceJoin(a, sep)
}

// SliceFilter delegates to the internal base implementation.
func SliceFilter[T any](a []T, pred func(T) bool) []T {
	return base.SliceFilter(a, pred)
}

// SliceMap delegates to the internal base implementation.
func SliceMap[T, R any](a []T, fn func(T) R) []R {
	return base.SliceMap(a, fn)
}

// SliceSub delegates to the internal base implementation.
func SliceSub[T any](a []T, fromIndex, toIndex int) []T {
	return base.SliceSub(a, fromIndex, toIndex)
}

// SliceConcat delegates to the internal base implementation.
func SliceConcat[T any](slices ...[]T) []T {
	return base.SliceConcat(slices...)
}

// Base64EncodeStr delegates to the internal base implementation.
func Base64EncodeStr(s string) string {
	return base.Base64EncodeStr(s)
}

// Base64DecodeStr delegates to the internal base implementation.
func Base64DecodeStr(s string) (string, error) {
	return base.Base64DecodeStr(s)
}

// Base64URLEncode delegates to the internal base implementation.
func Base64URLEncode(data []byte) string {
	return base.Base64URLEncode(data)
}

// Base64URLDecode delegates to the internal base implementation.
func Base64URLDecode(s string) ([]byte, error) {
	return base.Base64URLDecode(s)
}

// HexEncodeStr delegates to the internal base implementation.
func HexEncodeStr(s string) string {
	return base.HexEncodeStr(s)
}

// HexDecodeStr delegates to the internal base implementation.
func HexDecodeStr(s string) (string, error) {
	return base.HexDecodeStr(s)
}

// URLEncode delegates to the internal base implementation.
func URLEncode(s string) string {
	return base.URLEncode(s)
}

// URLDecode delegates to the internal base implementation.
func URLDecode(s string) (string, error) {
	return base.URLDecode(s)
}

// MapIsEmpty delegates to the internal base implementation.
func MapIsEmpty[K comparable, V any](m map[K]V) bool {
	return base.MapIsEmpty(m)
}

// MapIsNotEmpty delegates to the internal base implementation.
func MapIsNotEmpty[K comparable, V any](m map[K]V) bool {
	return base.MapIsNotEmpty(m)
}

// MapInverse delegates to the internal base implementation.
func MapInverse[K, V comparable](m map[K]V) map[V]K {
	return base.MapInverse(m)
}

// MapMerge delegates to the internal base implementation.
func MapMerge[K comparable, V any](maps ...map[K]V) map[K]V {
	return base.MapMerge(maps...)
}

// Subtract delegates to the internal base implementation.
func Subtract[T comparable](a, b []T) []T {
	return base.Subtract(a, b)
}

// Page delegates to the internal base implementation.
func Page[T any](a []T, pageNo, pageSize int) []T {
	return base.Page(a, pageNo, pageSize)
}

// ToString delegates to the internal base implementation.
func ToString(v any) string {
	return base.ToString(v)
}

// ToStringDefault delegates to the internal base implementation.
func ToStringDefault(v any, def string) string {
	return base.ToStringDefault(v, def)
}

// ToInt delegates to the internal base implementation.
func ToInt(v any) int {
	return base.ToInt(v)
}

// ToIntDefault delegates to the internal base implementation.
func ToIntDefault(v any, def int) int {
	return base.ToIntDefault(v, def)
}

// ToInt64 delegates to the internal base implementation.
func ToInt64(v any) int64 {
	return base.ToInt64(v)
}

// ToInt64Default delegates to the internal base implementation.
func ToInt64Default(v any, def int64) int64 {
	return base.ToInt64Default(v, def)
}

// ToFloat64 delegates to the internal base implementation.
func ToFloat64(v any) float64 {
	return base.ToFloat64(v)
}

// ToFloat64Default delegates to the internal base implementation.
func ToFloat64Default(v any, def float64) float64 {
	return base.ToFloat64Default(v, def)
}

// ToBool delegates to the internal base implementation.
func ToBool(v any) bool {
	return base.ToBool(v)
}

// ToBoolDefault delegates to the internal base implementation.
func ToBoolDefault(v any, def bool) bool {
	return base.ToBoolDefault(v, def)
}

// ToBytes delegates to the internal base implementation.
func ToBytes(v any) []byte {
	return base.ToBytes(v)
}

// Today delegates to the internal base implementation.
func Today() time.Time {
	return base.Today()
}

// FormatDate delegates to the internal base implementation.
func FormatDate(t time.Time, layout string) string {
	return base.FormatDate(t, layout)
}

// FormatDateOnly delegates to the internal base implementation.
func FormatDateOnly(t time.Time) string {
	return base.FormatDateOnly(t)
}

// FormatTimeOnly delegates to the internal base implementation.
func FormatTimeOnly(t time.Time) string {
	return base.FormatTimeOnly(t)
}

// BeginOfMonth delegates to the internal base implementation.
func BeginOfMonth(t time.Time) time.Time {
	return base.BeginOfMonth(t)
}

// EndOfMonth delegates to the internal base implementation.
func EndOfMonth(t time.Time) time.Time {
	return base.EndOfMonth(t)
}

// BeginOfYear delegates to the internal base implementation.
func BeginOfYear(t time.Time) time.Time {
	return base.BeginOfYear(t)
}

// EndOfYear delegates to the internal base implementation.
func EndOfYear(t time.Time) time.Time {
	return base.EndOfYear(t)
}

// OffsetDay delegates to the internal base implementation.
func OffsetDay(t time.Time, days int) time.Time {
	return base.OffsetDay(t, days)
}

// OffsetMonth delegates to the internal base implementation.
func OffsetMonth(t time.Time, months int) time.Time {
	return base.OffsetMonth(t, months)
}

// OffsetYear delegates to the internal base implementation.
func OffsetYear(t time.Time, years int) time.Time {
	return base.OffsetYear(t, years)
}

// OffsetHour delegates to the internal base implementation.
func OffsetHour(t time.Time, hours int) time.Time {
	return base.OffsetHour(t, hours)
}

// OffsetMinute delegates to the internal base implementation.
func OffsetMinute(t time.Time, minutes int) time.Time {
	return base.OffsetMinute(t, minutes)
}

// OffsetSecond delegates to the internal base implementation.
func OffsetSecond(t time.Time, seconds int) time.Time {
	return base.OffsetSecond(t, seconds)
}

// IsSameDay delegates to the internal base implementation.
func IsSameDay(a, b time.Time) bool {
	return base.IsSameDay(a, b)
}

// ReadAll delegates to the internal base implementation.
func ReadAll(r io.Reader) ([]byte, error) {
	return base.ReadAll(r)
}

// ReadString delegates to the internal base implementation.
func ReadString(r io.Reader) (string, error) {
	return base.ReadString(r)
}

// ReadLines delegates to the internal base implementation.
func ReadLines(r io.Reader) ([]string, error) {
	return base.ReadLines(r)
}

// IsFile delegates to the internal base implementation.
func IsFile(path string) bool {
	return base.IsFile(path)
}

// IsDirectory delegates to the internal base implementation.
func IsDirectory(path string) bool {
	return base.IsDirectory(path)
}

// FileReadBytes delegates to the internal base implementation.
func FileReadBytes(path string) ([]byte, error) {
	return base.FileReadBytes(path)
}

// FileReadLines delegates to the internal base implementation.
func FileReadLines(path string) ([]string, error) {
	return base.FileReadLines(path)
}

// FileWriteBytes delegates to the internal base implementation.
func FileWriteBytes(path string, data []byte) error {
	return base.FileWriteBytes(path, data)
}

// FileAppendString delegates to the internal base implementation.
func FileAppendString(path, content string) error {
	return base.FileAppendString(path, content)
}

// Mkdir delegates to the internal base implementation.
func Mkdir(dir string) error {
	return base.Mkdir(dir)
}

// Touch delegates to the internal base implementation.
func Touch(path string) error {
	return base.Touch(path)
}

// Del delegates to the internal base implementation.
func Del(path string) error {
	return base.Del(path)
}

// FileCopy delegates to the internal base implementation.
func FileCopy(src, dst string) error {
	return base.FileCopy(src, dst)
}

// MainName delegates to the internal base implementation.
func MainName(path string) string {
	return base.MainName(path)
}

// Extension delegates to the internal base implementation.
func Extension(path string) string {
	return base.Extension(path)
}

// FileSize delegates to the internal base implementation.
func FileSize(path string) int64 {
	return base.FileSize(path)
}

// ReaderFromString delegates to the internal base implementation.
func ReaderFromString(s string) io.Reader {
	return base.ReaderFromString(s)
}

// IsBlankChar delegates to the internal base implementation.
func IsBlankChar(r rune) bool {
	return base.IsBlankChar(r)
}

// IsLetter delegates to the internal base implementation.
func IsLetter(r rune) bool {
	return base.IsLetter(r)
}

// IsDigit delegates to the internal base implementation.
func IsDigit(r rune) bool {
	return base.IsDigit(r)
}

// IsAscii delegates to the internal base implementation.
func IsAscii(r rune) bool {
	return base.IsAscii(r)
}

// IsLetterOrDigit delegates to the internal base implementation.
func IsLetterOrDigit(r rune) bool {
	return base.IsLetterOrDigit(r)
}

// BoolNegate delegates to the internal base implementation.
func BoolNegate(b bool) bool {
	return base.BoolNegate(b)
}

// BoolToInt delegates to the internal base implementation.
func BoolToInt(b bool) int {
	return base.BoolToInt(b)
}

// BoolAnd delegates to the internal base implementation.
func BoolAnd(bs ...bool) bool {
	return base.BoolAnd(bs...)
}

// BoolOr delegates to the internal base implementation.
func BoolOr(bs ...bool) bool {
	return base.BoolOr(bs...)
}

// AdditiveHash delegates to the internal base implementation.
func AdditiveHash(s string, prime int) int {
	return base.AdditiveHash(s, prime)
}

// FnvHash delegates to the internal base implementation.
func FnvHash(s string) uint32 {
	return base.FnvHash(s)
}

// SHA1Hex delegates to the internal base implementation.
func SHA1Hex(s string) string {
	return base.SHA1Hex(s)
}

// SHA256Hex delegates to the internal base implementation.
func SHA256Hex(s string) string {
	return base.SHA256Hex(s)
}

// IsMobile delegates to the internal base implementation.
func IsMobile(s string) bool {
	return base.IsMobile(s)
}

// IsChinese delegates to the internal base implementation.
func IsChinese(s string) bool {
	return base.IsChinese(s)
}

// IsNumberStr delegates to the internal base implementation.
func IsNumberStr(s string) bool {
	return base.IsNumberStr(s)
}

// ReMatch delegates to the internal base implementation.
func ReMatch(pattern, s string) bool {
	return base.ReMatch(pattern, s)
}

// ReFind delegates to the internal base implementation.
func ReFind(pattern, s string) string {
	return base.ReFind(pattern, s)
}

// ReFindAll delegates to the internal base implementation.
func ReFindAll(pattern, s string) []string {
	return base.ReFindAll(pattern, s)
}

// ReReplace delegates to the internal base implementation.
func ReReplace(pattern, s, replacement string) string {
	return base.ReReplace(pattern, s, replacement)
}

// DefaultIfNil delegates to the internal base implementation.
func DefaultIfNil[T any](v *T, def T) T {
	return base.DefaultIfNil(v, def)
}

// EscapeHTML delegates to the internal base implementation.
func EscapeHTML(s string) string {
	return base.EscapeHTML(s)
}

// UnescapeHTML delegates to the internal base implementation.
func UnescapeHTML(s string) string {
	return base.UnescapeHTML(s)
}

// ToCamelCase delegates to the internal base implementation.
func ToCamelCase(s string) string {
	return base.ToCamelCase(s)
}

// ToPascalCase delegates to the internal base implementation.
func ToPascalCase(s string) string {
	return base.ToPascalCase(s)
}

// ToUnderlineCase delegates to the internal base implementation.
func ToUnderlineCase(s string) string {
	return base.ToUnderlineCase(s)
}

// ToKebabCase delegates to the internal base implementation.
func ToKebabCase(s string) string {
	return base.ToKebabCase(s)
}

// NumberAdd delegates to the internal base implementation.
func NumberAdd(a, b float64) float64 {
	return base.NumberAdd(a, b)
}

// NumberSub delegates to the internal base implementation.
func NumberSub(a, b float64) float64 {
	return base.NumberSub(a, b)
}

// NumberMul delegates to the internal base implementation.
func NumberMul(a, b float64) float64 {
	return base.NumberMul(a, b)
}

// NumberDiv delegates to the internal base implementation.
func NumberDiv(a, b float64, scale int) float64 {
	return base.NumberDiv(a, b, scale)
}

// Round delegates to the internal base implementation.
func Round(v float64, scale int) float64 {
	return base.Round(v, scale)
}

// IsInteger delegates to the internal base implementation.
func IsInteger(s string) bool {
	return base.IsInteger(s)
}

// IsDigits delegates to the internal base implementation.
func IsDigits(s string) bool {
	return base.IsDigits(s)
}

// Range delegates to the internal base implementation.
func Range(start, end, step int) []int {
	return base.Range(start, end, step)
}

// Equals delegates to the internal base implementation.
func Equals(a, b float64) bool {
	return base.Equals(a, b)
}

// DecimalFormat delegates to the internal base implementation.
func DecimalFormat(format string, v float64) string {
	return base.DecimalFormat(format, v)
}

// RandomIntRange delegates to the internal base implementation.
func RandomIntRange(min, max int) int {
	return base.RandomIntRange(min, max)
}

// RandomLong delegates to the internal base implementation.
func RandomLong() int64 {
	return base.RandomLong()
}

// RandomFloat delegates to the internal base implementation.
func RandomFloat() float64 {
	return base.RandomFloat()
}

// RandomBool delegates to the internal base implementation.
func RandomBool() bool {
	return base.RandomBool()
}

// RandomBytes delegates to the internal base implementation.
func RandomBytes(n int) []byte {
	return base.RandomBytes(n)
}

// RandomNumbers delegates to the internal base implementation.
func RandomNumbers(n int) string {
	return base.RandomNumbers(n)
}

// RandomStringUpper delegates to the internal base implementation.
func RandomStringUpper(n int) string {
	return base.RandomStringUpper(n)
}

// RandomStringFrom delegates to the internal base implementation.
func RandomStringFrom(charset string, n int) string {
	return base.RandomStringFrom(charset, n)
}

// RandomEle delegates to the internal base implementation.
func RandomEle[T any](a []T) T {
	return base.RandomEle(a)
}

// SimpleUUID delegates to the internal base implementation.
func SimpleUUID() string {
	return base.SimpleUUID()
}

// NanoIdN delegates to the internal base implementation.
func NanoIdN(n int) string {
	return base.NanoIdN(n)
}

// HasEmpty delegates to the internal base implementation.
func HasEmpty(strs ...string) bool {
	return base.HasEmpty(strs...)
}

// HasBlank delegates to the internal base implementation.
func HasBlank(strs ...string) bool {
	return base.HasBlank(strs...)
}

// IsAllEmpty delegates to the internal base implementation.
func IsAllEmpty(strs ...string) bool {
	return base.IsAllEmpty(strs...)
}

// IsAllBlank delegates to the internal base implementation.
func IsAllBlank(strs ...string) bool {
	return base.IsAllBlank(strs...)
}

// Trim delegates to the internal base implementation.
func Trim(s string) string {
	return base.Trim(s)
}

// TrimToEmpty delegates to the internal base implementation.
func TrimToEmpty(s string) string {
	return base.TrimToEmpty(s)
}

// TrimStart delegates to the internal base implementation.
func TrimStart(s string) string {
	return base.TrimStart(s)
}

// TrimEnd delegates to the internal base implementation.
func TrimEnd(s string) string {
	return base.TrimEnd(s)
}

// Sub delegates to the internal base implementation.
func Sub(s string, fromIndex, toIndex int) string {
	return base.Sub(s, fromIndex, toIndex)
}

// SubBefore delegates to the internal base implementation.
func SubBefore(s, sep string, isLastSeparator bool) string {
	return base.SubBefore(s, sep, isLastSeparator)
}

// SubAfter delegates to the internal base implementation.
func SubAfter(s, sep string, isLastSeparator bool) string {
	return base.SubAfter(s, sep, isLastSeparator)
}

// Split delegates to the internal base implementation.
func Split(s, sep string) []string {
	return base.Split(s, sep)
}

// SplitTrim delegates to the internal base implementation.
func SplitTrim(s, sep string) []string {
	return base.SplitTrim(s, sep)
}

// Repeat delegates to the internal base implementation.
func Repeat(s string, n int) string {
	return base.Repeat(s, n)
}

// PadLeft delegates to the internal base implementation.
func PadLeft(s string, length int, pad rune) string {
	return base.PadLeft(s, length, pad)
}

// PadRight delegates to the internal base implementation.
func PadRight(s string, length int, pad rune) string {
	return base.PadRight(s, length, pad)
}

// ContainsAny delegates to the internal base implementation.
func ContainsAny(s string, subs ...string) bool {
	return base.ContainsAny(s, subs...)
}

// ContainsAll delegates to the internal base implementation.
func ContainsAll(s string, subs ...string) bool {
	return base.ContainsAll(s, subs...)
}

// StartsWith delegates to the internal base implementation.
func StartsWith(s, prefix string) bool {
	return base.StartsWith(s, prefix)
}

// EndsWith delegates to the internal base implementation.
func EndsWith(s, suffix string) bool {
	return base.EndsWith(s, suffix)
}

// Reverse delegates to the internal base implementation.
func Reverse(s string) string {
	return base.Reverse(s)
}

// RemovePrefix delegates to the internal base implementation.
func RemovePrefix(s, prefix string) string {
	return base.RemovePrefix(s, prefix)
}

// RemoveSuffix delegates to the internal base implementation.
func RemoveSuffix(s, suffix string) string {
	return base.RemoveSuffix(s, suffix)
}
