package vcaptcha

import captcha "github.com/imajinyun/go-knifer/internal/captcha"

// Code generated by internal facade audit; DO NOT EDIT.

// VerifyIgnoreCase delegates to the internal captcha implementation.
func VerifyIgnoreCase(code, input string) bool {
	return captcha.VerifyIgnoreCase(code, input)
}

// NewMathGeneratorWith delegates to the internal captcha implementation.
func NewMathGeneratorWith(numberLength int, resultHasNegativeNumber bool) *MathGenerator {
	return captcha.NewMathGeneratorWith(numberLength, resultHasNegativeNumber)
}

// CreateLineCaptcha delegates to the internal captcha implementation.
func CreateLineCaptcha(width, height int) *LineCaptcha {
	return captcha.CreateLineCaptcha(width, height)
}

// CreateLineCaptchaWith delegates to the internal captcha implementation.
func CreateLineCaptchaWith(width, height, codeCount, lineCount int) *LineCaptcha {
	return captcha.CreateLineCaptchaWith(width, height, codeCount, lineCount)
}

// CreateLineCaptchaByGenerator delegates to the internal captcha implementation.
func CreateLineCaptchaByGenerator(width, height int, generator CodeGenerator, lineCount int) *LineCaptcha {
	return captcha.CreateLineCaptchaByGenerator(width, height, generator, lineCount)
}

// CreateCircleCaptcha delegates to the internal captcha implementation.
func CreateCircleCaptcha(width, height int) *CircleCaptcha {
	return captcha.CreateCircleCaptcha(width, height)
}

// CreateCircleCaptchaWith delegates to the internal captcha implementation.
func CreateCircleCaptchaWith(width, height, codeCount, circleCount int) *CircleCaptcha {
	return captcha.CreateCircleCaptchaWith(width, height, codeCount, circleCount)
}

// CreateCircleCaptchaByGenerator delegates to the internal captcha implementation.
func CreateCircleCaptchaByGenerator(width, height int, generator CodeGenerator, circleCount int) *CircleCaptcha {
	return captcha.CreateCircleCaptchaByGenerator(width, height, generator, circleCount)
}

// CreateShearCaptcha delegates to the internal captcha implementation.
func CreateShearCaptcha(width, height int) *ShearCaptcha {
	return captcha.CreateShearCaptcha(width, height)
}

// CreateShearCaptchaWith delegates to the internal captcha implementation.
func CreateShearCaptchaWith(width, height, codeCount, thickness int) *ShearCaptcha {
	return captcha.CreateShearCaptchaWith(width, height, codeCount, thickness)
}

// CreateShearCaptchaByGenerator delegates to the internal captcha implementation.
func CreateShearCaptchaByGenerator(width, height int, generator CodeGenerator, thickness int) *ShearCaptcha {
	return captcha.CreateShearCaptchaByGenerator(width, height, generator, thickness)
}

// CreateGifCaptcha delegates to the internal captcha implementation.
func CreateGifCaptcha(width, height int) *GifCaptcha {
	return captcha.CreateGifCaptcha(width, height)
}

// CreateGifCaptchaWith delegates to the internal captcha implementation.
func CreateGifCaptchaWith(width, height, codeCount int) *GifCaptcha {
	return captcha.CreateGifCaptchaWith(width, height, codeCount)
}

// CreateGifCaptchaByGenerator delegates to the internal captcha implementation.
func CreateGifCaptchaByGenerator(width, height int, generator CodeGenerator) *GifCaptcha {
	return captcha.CreateGifCaptchaByGenerator(width, height, generator)
}
