package vcaptcha

import captcha "github.com/imajinyun/go-knifer/internal/captcha"

// Code generated by internal facade audit; DO NOT EDIT.

// VerifyIgnoreCase delegates to the internal captcha implementation.
func VerifyIgnoreCase(code, input string) bool {
	return captcha.VerifyIgnoreCase(code, input)
}

// NewMathGeneratorWith delegates to the internal captcha implementation.
func NewMathGeneratorWith(numberLength int, resultHasNegativeNumber bool) *MathGenerator {
	return captcha.NewMathGeneratorWith(numberLength, resultHasNegativeNumber)
}
