package vcache

import (
	"time"

	cache "github.com/imajinyun/go-knifer/internal/cache"
)

// Code generated by internal facade audit; DO NOT EDIT.

// NewFIFOCache delegates to the internal cache implementation.
func NewFIFOCache[K comparable, V any](capacity int) *FIFOCache[K, V] {
	return &FIFOCache[K, V]{FIFOCache: cache.NewFIFOCache[K, V](capacity)}
}

// NewFIFOCacheWithTimeout delegates to the internal cache implementation.
func NewFIFOCacheWithTimeout[K comparable, V any](capacity int, timeout time.Duration) *FIFOCache[K, V] {
	return &FIFOCache[K, V]{FIFOCache: cache.NewFIFOCacheWithTimeout[K, V](capacity, timeout)}
}

// NewLFUCache delegates to the internal cache implementation.
func NewLFUCache[K comparable, V any](capacity int) *LFUCache[K, V] {
	return &LFUCache[K, V]{LFUCache: cache.NewLFUCache[K, V](capacity)}
}

// NewLFUCacheWithTimeout delegates to the internal cache implementation.
func NewLFUCacheWithTimeout[K comparable, V any](capacity int, timeout time.Duration) *LFUCache[K, V] {
	return &LFUCache[K, V]{LFUCache: cache.NewLFUCacheWithTimeout[K, V](capacity, timeout)}
}

// NewLRUCache delegates to the internal cache implementation.
func NewLRUCache[K comparable, V any](capacity int) *LRUCache[K, V] {
	return &LRUCache[K, V]{LRUCache: cache.NewLRUCache[K, V](capacity)}
}

// NewLRUCacheWithTimeout delegates to the internal cache implementation.
func NewLRUCacheWithTimeout[K comparable, V any](capacity int, timeout time.Duration) *LRUCache[K, V] {
	return &LRUCache[K, V]{LRUCache: cache.NewLRUCacheWithTimeout[K, V](capacity, timeout)}
}

// NewTimedCache delegates to the internal cache implementation.
func NewTimedCache[K comparable, V any](timeout time.Duration) *TimedCache[K, V] {
	return &TimedCache[K, V]{TimedCache: cache.NewTimedCache[K, V](timeout)}
}

// NewNo delegates to the internal cache implementation.
func NewNo[K comparable, V any]() *NoCache[K, V] {
	return &NoCache[K, V]{NoCache: cache.NewNo[K, V]()}
}

// NewWeakCache delegates to the internal cache implementation.
func NewWeakCache[K comparable, V any](timeout time.Duration) *WeakCache[K, V] {
	return &WeakCache[K, V]{WeakCache: cache.NewWeakCache[K, V](timeout)}
}
